Adding helm
On clean install, without adding the following to main.tf, it fails to create the cluster.
```
provider "helm" {
  version = "1.3.2"
}
```
It gives the following error:
```
module.eks-jx.module.cluster.helm_release.jx-git-operator[0]: Creating...
Error: provider not configured: you must configure a path to your kubeconfig
or explicitly supply credentials via the provider block or environment variables.
See our authentication documentation at: https://registry.terraform.io/providers/hashicorp/helm/latest/docs#authentication
```

After adding it to main.tf, it warns that adding provider in main.tf is deprecated, and it should be added to required providers instead, so here is the pull request.